var Data = [          // mang chua thong tin san pham
    {
        id: 1,
        ten: "Sản phẩm 1",
        gia: 12500000,
        loai: "PC",
        mota: "Intel i3-12100F / VGA RX 6500XT (Powered by ASUS)",
        image: "img/sp1.jpg",
        mota_chitiet: "	Màn hình: ViewSonic VA2215-H 22 100Hz FHD, Bàn phím: DareU EK106 Pro Haze Blue Cloud switch, Chuột: Logitech G502 HERO",
    },
    {
        id: 2,
        ten: "Sản Phảm 2",
        gia: 21000000,
        loai: "PC",
        mota: "Intel i5-12400F / VGA RTX 4060 (Powered by NZXT)",
        image: "img/sp2.jpg",
        mota_chitiet: "Màn hình: ACER EK221Q E3 22 IPS 100Hz, Bàn phím: Machenike K600-B82W White Tri-Mode GR Silver switch, Chuột: Razer DeathAdder Essential (RZ01-03850100-R3M1)", 
    },
    {
        id: 3,
        ten: "Sản Phẩm 3",
        gia: 30000000,
        loai: "PC",
        mota: "Intel i7-14700F / VGA RTX 3060 (Powered by ACER)",
        image: "img/sp3.jpg",
        mota_chitiet: "Màn hình: LG 27GS75Q-B 27 IPS 2K 200Hz Gsync, Bàn phím: E-Dra không dây EK375 Pro Beta Brown Switch, Chuột: Logitech G102 LightSync White",
    },
    {
        id: 4,
        ten: "Laptop Acer Swift 3",
        gia: 12000000,
        loai: "Laptop",
        mota: "Laptop văn phòng mỏng nhẹ, hiệu năng cao, thiết kế sang trọng.",
        image: "img/laptop1-1.jpg",
        mota_chitiet: "CPU: Intel Core i5-1135G7, Ổ cứng: 512GB, RAM: 16GB, Card đồ họa: Intel Iris Xe Graphics",
    },
    {
        id: 5,
        ten: "Laptop gaming Gigabyte G5",
        gia: 22000000,
        loai: "Laptop",
        mota: "Laptop gaming hiệu năng cao, tản nhiệt tối ưu, thiết kế mạnh mẽ.",
        image: "img/laptop2-1.jpg",
        mota_chitiet: "CPU: Intel Core i5-12500H, Ổ cứng: 512GB, RAM: 16GB, Card đồ họa: RTX 4060 8GB",
    },
    {
        id: 6,
        ten: "Laptop ASUS Zenbook 14",
        gia: 18000000,
        loai: "Laptop",
        mota: "Laptop siêu mỏng nhẹ, sang trọng, thời lượng pin dài.",
        image: "img/laptop3-1.jpg",
        mota_chitiet: "CPU: AMD Ryzen 5 7530U, Ổ cứng: 512GB, RAM: 16GB, Card đồ họa: AMD Radeon Graphics",
    },
    {
        id: 7,
        ten: "Màn hình Gaming LG UltraGear 24GS50F-B 24 inch",
        gia: 2900000,
        loai: "Màn Hình",
        mota: "Độ trễ chỉ 1ms, 24 inch, 180Hz, Full HD",
        image: "img/ManHinh1.jpg",
        mota_chitiet: "Màn hình LG ULTRAGEAR 24GS50F-B 24 inch với tần số làm mới cao đến 180Hz giúp giảm thiểu các tình trạng trễ khung hình nhờ đó tái tạo hình ảnh rõ nét và mượt mà. Cùng với đó màn hình 24 inch này còn được trang bị tốc độ phản hồi nhanh 1ms MBR nhờ vậy người dùng có thể quan sát được các chuyển động một cách nhanh chóng, đặc biệt trong các trò chơi.",
    },
    {
        id: 8,
        ten: "Chuột Razer Deathadder Essential White",
        gia: 590000,
        loai: "Phụ Kiện",
        mota: "Chuột có dây, Led RGB",
        image: "img/PhuKien1.jpg",
        mota_chitiet: "Chuột gaming DeathAdder Essential White được Razer thiết kế với kiểu dáng công thái học (Ergonomic) cổ điển. Thiết kế đẹp mắt và khác biệt ở các dòng chuột máy tính khác tạo ra sự thoải mái, cho phép người chơi duy trì mức hiệu suất cao trong suốt thời gian chơi game dài, vì vậy bạn sẽ không bao giờ bị ngập ngừng trong các trận chiến nóng bỏng. Hứa hẹn đây sẽ là một trong những dòng chuột gaming dưới 1 triệu rất đáng trải nghiệm.",
    },
    {
        id: 9,
        ten: "Bàn Phím Cơ Akko 3098 Neon",
        gia: 890000,
        loai: "Phụ Kiện",
        mota: "Bàn phìm 1800-Compact (Rút gọn) có dây",
        image: "img/PhuKien2.jpg",
        mota_chitiet: "Cream Blue Pro switch Model: 3098 Neon (98 keys) Kết nối: USB Type-C , có thể tháo rời Backlit : Rainbow LED Kích thước: 382x134x40 mm | Trọng lượng 1kg Keycap PBT Double Shot, ASA profile Loại switch: AKKO Cream Yellow Pro/ Cream Blue Pro Hỗ trợ NKRO / Multimedia / Macro",
    },
];